In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [11]:
df = pd.read_csv('ex1data1.txt', header=None, names=['Population', 'Profit'])

In [12]:
df.head()

Population   Profit
0      6.1101  17.5920
1      5.5277   9.1302
2      8.5186  13.6620
3      7.0032  11.8540
4      5.8598   6.8233

In [13]:
df['Output'] = 1
df.loc[df.Population < 6.589400, 'Output'] = 0

In [14]:
df.describe()

Population     Profit     Output
count   97.000000  97.000000  97.000000
mean     8.159800   5.839135   0.505155
std      3.869884   5.510262   0.502571
min      5.026900  -2.680700   0.000000
25%      5.707700   1.986900   0.000000
50%      6.589400   4.562300   1.000000
75%      8.578100   7.046700   1.000000
max     22.203000  24.147000   1.000000

In [15]:
df.head()

Population   Profit  Output
0      6.1101  17.5920       0
1      5.5277   9.1302       0
2      8.5186  13.6620       1
3      7.0032  11.8540       1
4      5.8598   6.8233       0

In [79]:
X = df[['Population', 'Profit']]
y = df['Output']

In [88]:
from sklearn import linear_model
model = linear_model.LinearRegression()
model.fit(X,y.values.reshape(-1,1))

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [90]:
y_predA = model.predict(X)

In [100]:
model = linear_model.LinearRegression(fit_intercept=False)
model.fit(X,y.values.reshape(-1,1))

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=1, normalize=False)

In [101]:
y_predAA = model.predict(X)

In [68]:
X.loc[-1] = [1, 1]
X.index = X.index + 1  # shifting index
X = X.sort_index()

D:\Anaconda3\lib\site-packages\pandas\core\indexing.py:189: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [70]:
X

Population    Profit
0       1.0000   1.00000
1       6.1101  17.59200
2       5.5277   9.13020
3       8.5186  13.66200
4       7.0032  11.85400
5       5.8598   6.82330
6       8.3829  11.88600
7       7.4764   4.34830
8       8.5781  12.00000
9       6.4862   6.59870
10      5.0546   3.81660
11      5.7107   3.25220
12     14.1640  15.50500
13      5.7340   3.15510
14      8.4084   7.22580
15      5.6407   0.71618
16      5.3794   3.51290
17      6.3654   5.30480
18      5.1301   0.56077
19      6.4296   3.65180
20      7.0708   5.38930
21      6.1891   3.13860
22     20.2700  21.76700
23      5.4901   4.26300
24      6.3261   5.18750
25      5.5649   3.08250
26     18.9450  22.63800
27     12.8280  13.50100
28     10.9570   7.04670
29     13.1760  14.69200
..         ...       ...
68     10.2360   7.77540
69      5.4994   1.01730
70     20.3410  20.99200
71     10.1360   6.67990
72      7.3345   4.02590
73      6.0062   1.27840
74      7.2259   3.34110
75      5.0269  -2.68070
76      6.5479   0.29678
77      7.5386   3.88450
78      5.0365   5.70140
79     10.2740   6.75260
80      5.1077   2.05760
81      5.7292   0.47953
82      5.1884   0.20421
83      6.3557   0.67861
84      9.7687   7.54350
85      6.5159   5.34360
86      8.5172   4.24150
87      9.1802   6.79810
88      6.0020   0.92695
89      5.5204   0.15200
90      5.0594   2.82140
91      5.7077   1.84510
92      7.6366   4.29590
93      5.8707   7.20290
94      5.3054   1.98690
95      8.2934   0.14454
96     13.3940   9.05510
97      5.4369   0.61705

[98 rows x 2 columns]

In [20]:
Y = XT . B

NameError: name 'XT' is not defined

In [ ]:
B = 

In [80]:
X.values

array([[ 6.1101 , 17.592  ],
       [ 5.5277 ,  9.1302 ],
       [ 8.5186 , 13.662  ],
       [ 7.0032 , 11.854  ],
       [ 5.8598 ,  6.8233 ],
       [ 8.3829 , 11.886  ],
       [ 7.4764 ,  4.3483 ],
       [ 8.5781 , 12.     ],
       [ 6.4862 ,  6.5987 ],
       [ 5.0546 ,  3.8166 ],
       [ 5.7107 ,  3.2522 ],
       [14.164  , 15.505  ],
       [ 5.734  ,  3.1551 ],
       [ 8.4084 ,  7.2258 ],
       [ 5.6407 ,  0.71618],
       [ 5.3794 ,  3.5129 ],
       [ 6.3654 ,  5.3048 ],
       [ 5.1301 ,  0.56077],
       [ 6.4296 ,  3.6518 ],
       [ 7.0708 ,  5.3893 ],
       [ 6.1891 ,  3.1386 ],
       [20.27   , 21.767  ],
       [ 5.4901 ,  4.263  ],
       [ 6.3261 ,  5.1875 ],
       [ 5.5649 ,  3.0825 ],
       [18.945  , 22.638  ],
       [12.828  , 13.501  ],
       [10.957  ,  7.0467 ],
       [13.176  , 14.692  ],
       [22.203  , 24.147  ],
       [ 5.2524 , -1.22   ],
       [ 6.5894 ,  5.9966 ],
       [ 9.2482 , 12.134  ],
       [ 5.8918 ,  1.8495 ],
       [ 8.211

In [81]:
X_matrix = X.values

In [82]:
y_matrix = y.values.reshape(-1,1)
y_matrix

array([[0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
    

In [83]:
b = np.linalg.inv(X_matrix.T.dot(X_matrix)).dot(X_matrix.T).dot(y_matrix)

In [84]:
b

array([[0.05609494],
       [0.01165548]])

In [85]:
yhat = X_matrix.dot(b)

In [98]:
yhat

array([[0.54778891],
       [0.41649288],
       [0.63708755],
       [0.53100816],
       [0.40823398],
       [0.60877533],
       [0.47006976],
       [0.62105379],
       [0.44075404],
       [0.32802181],
       [0.35824735],
       [0.97524699],
       [0.35842261],
       [0.55588889],
       [0.32476217],
       [0.34270167],
       [0.41889674],
       [0.29430872],
       [0.40323153],
       [0.459451  ],
       [0.3837591 ],
       [1.39074933],
       [0.35765416],
       [0.41532502],
       [0.34809077],
       [1.32657545],
       [0.87694657],
       [0.69676497],
       [0.91034928],
       [1.5269209 ],
       [0.2804134 ],
       [0.43952527],
       [0.66020485],
       [0.352057  ],
       [0.53685833],
       [0.49819942],
       [0.50211767],
       [0.35402979],
       [0.83795318],
       [0.42046845],
       [0.30978684],
       [0.43166386],
       [0.71952902],
       [0.35232174],
       [0.51738846],
       [0.41008218],
       [0.34424832],
       [0.346

In [75]:
XTX = np.dot(X_matrix.T, X_matrix)

In [76]:
inverse = np.linalg.inv(XTX)

In [77]:
beta = np.dot(inverse, X_matrix.T)

In [78]:
beta = np.dot(beta, y_matrix)

ValueError: shapes (2,98) and (97,1) not aligned: 98 (dim 1) != 97 (dim 0)

In [44]:
beta

array([[0.05609494],
       [0.01165548]])

In [92]:
y_predB = np.dot(X_matrix, beta)

In [97]:
y_predB

array([[ 2.97786488e-03,  1.46370114e-01,  5.66762707e-02, ...,
        -6.62709532e-02, -8.55060543e-03, -3.76147283e-02],
       [ 1.51536737e-03,  5.66762707e-02,  2.32538729e-02, ...,
        -2.10850990e-02,  2.37831567e-03, -1.16658109e-02],
       [ 2.26436276e-03,  8.27841839e-02,  3.41496965e-02, ...,
        -3.01545612e-02,  4.27382130e-03, -1.66320398e-02],
       ...,
       [-8.09489440e-05, -6.62709532e-02, -2.10850990e-02, ...,
         4.60110227e-02,  2.37720212e-02,  2.71713577e-02],
       [ 1.40172541e-03, -8.55060543e-03,  2.37831567e-03, ...,
         2.37720212e-02,  2.52424134e-02,  1.48056636e-02],
       [ 3.76628756e-05, -3.76147283e-02, -1.16658109e-02, ...,
         2.71713577e-02,  1.48056636e-02,  1.60912089e-02]])

In [102]:
for i in range(0, len(y_predA)):
    print(y_predA[i], yhat[i], y_predAA[i])

[0.37646369] [0.54778891] [0.54778891]
[0.3082591] [0.41649288] [0.41649288]
[0.55417024] [0.63708755] [0.63708755]
[0.43088303] [0.53100816] [0.53100816]
[0.32803058] [0.40823398] [0.40823398]
[0.53880289] [0.60877533] [0.60877533]
[0.44774488] [0.47006976] [0.47006976]
[0.55436489] [0.62105379] [0.62105379]
[0.37638638] [0.44075404] [0.44075404]
[0.25703728] [0.32802181] [0.32802181]
[0.30680337] [0.35824735] [0.35824735]
[1.00034228] [0.97524699] [0.97524699]
[0.30836413] [0.35842261] [0.35842261]
[0.52830219] [0.55588889] [0.55588889]
[0.29453342] [0.32476217] [0.32476217]
[0.28160867] [0.34270167] [0.34270167]
[0.36347607] [0.41889674] [0.41889674]
[0.25420949] [0.29430872] [0.29430872]
[0.3640622] [0.40323153] [0.40323153]
[0.418835] [0.459451] [0.459451]
[0.34388943] [0.3837591] [0.3837591]
[1.49436081] [1.39074933] [1.39074933]
[0.2922717] [0.35765416] [0.35765416]
[0.36009] [0.41532502] [0.41532502]
[0.29495304] [0.34809077] [0.34809077]
[1.39313705] [1.32657545] [1.32657545]
